name: Testing - Reusable Workflow
on: 
   workflow_call:
    # inputs:
    #      ingress-url:
    #         required: true
    #         type: string
    #         description: "Provide the Ingress URL"
    secrets:
      mongo_passwd: 
        required: true
      mongo_username:
        required: true
    inputs:
        mongo_url:
            required: true
            type: string

jobs:
    unit-testing:
      name: Unit Testing
      runs-on: ubuntu-latest
      container: node:20
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4


        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: '${{ runner.os }}-node-modules-${{ hashFiles(''package-lock.json'') }}'


        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          run: npm test

        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml


