on:
  workflow_call: 
    secrets:
      githut_token:
        required: true
jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4.2.2

    - name: DockerLogin
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: 'ghcr.io/${{ github.repository_owner}}/solar-system:${{ github.sha }}'
        context: .